### ISSUE TITLE
How to deal with TEXBAT data

### ISSUE THREAD

**Issue by zzz597** [nlsfi/FGI-GSRx#3]
Thank you very much for sharing, but I have a question. How can we modify the parameters to make this software receiver successfully process TEXBAT data?

**Comment by Imtiaz08** [comment]
did you find any solution please?

**Comment by OPdev101** [comment]
Any solutions? Response would be highly appreciated.

**Comment by zahidulbhuiyan** [comment]
Hi!

Please find attached the configuration file that you can use/modify to run to run FGI-GSRx with TEXBAT scenarios. Good luck!

Zahid
[defaultReceiverConfiguration_TEXBAT_Senario1.txt](https://github.com/nlsfi/FGI-GSRx/files/15126616/defaultReceiverConfiguration_TEXBAT_Senario1.txt)
![TEXBAT_Scenario_1_PositionDeviation_FGI-GSRxv2 0 0](https://github.com/nlsfi/FGI-GSRx/assets/48213477/3419758a-98ce-46e9-b73f-9a06297a8b0c)

**Comment by tortuga3750** [comment]
Hi Zahid, could you please provide parameters file for OAKBAT dataset?
If you can do it in GPS, I would appreciate it.

**Comment by OPdev101** [comment]
Here are all the parameters file for TEXBAT DATASETS:

[complete_Texbat_Dataset-cleanDynamic_GPS_L1_CA.txt](https://github.com/user-attachments/files/17080580/complete_Texbat_Dataset-cleanDynamic_GPS_L1_CA.txt)
[complete_Texbat_Dataset-cleanStatic_GPS_L1_CA.txt](https://github.com/user-attachments/files/17080582/complete_Texbat_Dataset-cleanStatic_GPS_L1_CA.txt)
[complete_Texbat_Dataset-ds1_GPS_L1_CA.txt](https://github.com/user-attachments/files/17080583/complete_Texbat_Dataset-ds1_GPS_L1_CA.txt)
[complete_Texbat_Dataset-ds2_GPS_L1_CA.txt](https://github.com/user-attachments/files/17080584/complete_Texbat_Dataset-ds2_GPS_L1_CA.txt)
[complete_Texbat_Dataset-ds3_GPS_L1_CA.txt](https://github.com/user-attachments/files/17080585/complete_Texbat_Dataset-ds3_GPS_L1_CA.txt)
[complete_Texbat_Dataset-ds4_GPS_L1_CA.txt](https://github.com/user-attachments/files/17080586/complete_Texbat_Dataset-ds4_GPS_L1_CA.txt)
[complete_Texbat_Dataset-ds5_GPS_L1_CA.txt](https://github.com/user-attachments/files/17080587/complete_Texbat_Dataset-ds5_GPS_L1_CA.txt)
[complete_Texbat_Dataset-ds6_GPS_L1_CA.txt](https://github.com/user-attachments/files/17080588/complete_Texbat_Dataset-ds6_GPS_L1_CA.txt)
[complete_Texbat_Dataset-ds7_GPS_L1_CA.txt](https://github.com/user-attachments/files/17080589/complete_Texbat_Dataset-ds7_GPS_L1_CA.txt)
[complete_Texbat_Dataset-ds8_GPS_L1_CA.txt](https://github.com/user-attachments/files/17080590/complete_Texbat_Dataset-ds8_GPS_L1_CA.txt)

**Comment by tortuga3750** [comment]
> Here are all the parameters file for TEXBAT DATASETS:
> 
> [complete_Texbat_Dataset-cleanDynamic_GPS_L1_CA.txt](https://github.com/user-attachments/files/17080580/complete_Texbat_Dataset-cleanDynamic_GPS_L1_CA.txt) [complete_Texbat_Dataset-cleanStatic_GPS_L1_CA.txt](https://github.com/user-attachments/files/17080582/complete_Texbat_Dataset-cleanStatic_GPS_L1_CA.txt) [complete_Texbat_Dataset-ds1_GPS_L1_CA.txt](https://github.com/user-attachments/files/17080583/complete_Texbat_Dataset-ds1_GPS_L1_CA.txt) [complete_Texbat_Dataset-ds2_GPS_L1_CA.txt](https://github.com/user-attachments/files/17080584/complete_Texbat_Dataset-ds2_GPS_L1_CA.txt) [complete_Texbat_Dataset-ds3_GPS_L1_CA.txt](https://github.com/user-attachments/files/17080585/complete_Texbat_Dataset-ds3_GPS_L1_CA.txt) [complete_Texbat_Dataset-ds4_GPS_L1_CA.txt](https://github.com/user-attachments/files/17080586/complete_Texbat_Dataset-ds4_GPS_L1_CA.txt) [complete_Texbat_Dataset-ds5_GPS_L1_CA.txt](https://github.com/user-attachments/files/17080587/complete_Texbat_Dataset-ds5_GPS_L1_CA.txt) [complete_Texbat_Dataset-ds6_GPS_L1_CA.txt](https://github.com/user-attachments/files/17080588/complete_Texbat_Dataset-ds6_GPS_L1_CA.txt) [complete_Texbat_Dataset-ds7_GPS_L1_CA.txt](https://github.com/user-attachments/files/17080589/complete_Texbat_Dataset-ds7_GPS_L1_CA.txt) [complete_Texbat_Dataset-ds8_GPS_L1_CA.txt](https://github.com/user-attachments/files/17080590/complete_Texbat_Dataset-ds8_GPS_L1_CA.txt)

thank you so much..

**Comment by OPdev101** [comment]
> > Here are all the parameters file for TEXBAT DATASETS:
> 
> > 
> 
> > [complete_Texbat_Dataset-cleanDynamic_GPS_L1_CA.txt](https://github.com/user-attachments/files/17080580/complete_Texbat_Dataset-cleanDynamic_GPS_L1_CA.txt) [complete_Texbat_Dataset-cleanStatic_GPS_L1_CA.txt](https://github.com/user-attachments/files/17080582/complete_Texbat_Dataset-cleanStatic_GPS_L1_CA.txt) [complete_Texbat_Dataset-ds1_GPS_L1_CA.txt](https://github.com/user-attachments/files/17080583/complete_Texbat_Dataset-ds1_GPS_L1_CA.txt) [complete_Texbat_Dataset-ds2_GPS_L1_CA.txt](https://github.com/user-attachments/files/17080584/complete_Texbat_Dataset-ds2_GPS_L1_CA.txt) [complete_Texbat_Dataset-ds3_GPS_L1_CA.txt](https://github.com/user-attachments/files/17080585/complete_Texbat_Dataset-ds3_GPS_L1_CA.txt) [complete_Texbat_Dataset-ds4_GPS_L1_CA.txt](https://github.com/user-attachments/files/17080586/complete_Texbat_Dataset-ds4_GPS_L1_CA.txt) [complete_Texbat_Dataset-ds5_GPS_L1_CA.txt](https://github.com/user-attachments/files/17080587/complete_Texbat_Dataset-ds5_GPS_L1_CA.txt) [complete_Texbat_Dataset-ds6_GPS_L1_CA.txt](https://github.com/user-attachments/files/17080588/complete_Texbat_Dataset-ds6_GPS_L1_CA.txt) [complete_Texbat_Dataset-ds7_GPS_L1_CA.txt](https://github.com/user-attachments/files/17080589/complete_Texbat_Dataset-ds7_GPS_L1_CA.txt) [complete_Texbat_Dataset-ds8_GPS_L1_CA.txt](https://github.com/user-attachments/files/17080590/complete_Texbat_Dataset-ds8_GPS_L1_CA.txt)
> 
> 
> 
> thank you so much..

My pleasure. If you need any assistance please do let me know.

**Comment by zahidulbhuiyan** [comment]
This issue is closed.

**Comment by qqqhbg** [comment]
> 你好！
> 
> 请找到附件中的配置文件，您可以使用/修改该文件来运行带有 TEXBAT 方案的 FGI-GSRx。祝你好运！
> 
> 扎希德 [defaultReceiverConfiguration_TEXBAT_Senario1.txt](https://github.com/nlsfi/FGI-GSRx/files/15126616/defaultReceiverConfiguration_TEXBAT_Senario1.txt) ![TEXBAT_Scenario_1_PositionDeviation_FGI-GSRxv2 0 0](https://private-user-images.githubusercontent.com/48213477/325881130-3419758a-98ce-46e9-b73f-9a06297a8b0c.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU1Mzk1NTUsIm5iZiI6MTczNTUzOTI1NSwicGF0aCI6Ii80ODIxMzQ3Ny8zMjU4ODExMzAtMzQxOTc1OGEtOThjZS00NmU5LWI3M2YtOWEwNjI5N2E4YjBjLkpQRz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjMwVDA2MTQxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4Yjc2NWU1ZDFlOWNmMDlkYzA0MzQ1YjhhNzExZDU3OGYwZmUyNTk3YjllMDBjMzFkMjUyMTFkYjhiNDRjYzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.iJsI7THgcDMk5Ogm21nRu4pdv4dnBvUoM58R5eR9zMc)

I hope this email finds you well. I am reaching out to seek your assistance with an issue I encountered while simulating a 3D error plot in MATLAB.
After launching the simulation using the .bat file, I noticed that my MATLAB Command Window becomes unresponsive during the simulation process, even though the simulation is indeed running. Once the simulation is completed, the Command Window log displays the start time as 360-366 seconds, which seems to be a display bug. However, the main issue is that the resulting 3D error plot appears blank.
Could you kindly provide guidance on how to resolve the issue of the blank 3D error plot?
Thank you very much for taking the time to read my email. I would greatly appreciate it if you could reply and help me address this issue.

**Comment by clichao666** [comment]
Hello! It seems like you're experiencing an issue with FGI-GSRx. The TEXBAT data acquisition process runs fine but doesn't transition into tracking mode. It stops automatically after acquisition. Could you please help me understand why this is happening?

![Image](https://github.com/user-attachments/assets/cbf6458a-8230-4cc6-a685-802c1f2b0a93)
