### ISSUE TITLE
how can I calculate delta?

### ISSUE THREAD

**Issue by tortuga3750** [nlsfi/FGI-GSRx#6]
![delta_equation](https://github.com/nlsfi/FGI-GSRx/assets/174285106/b2bf8a02-925d-4051-9f56-379fecc65426)

![image](https://github.com/nlsfi/FGI-GSRx/assets/174285106/01db727d-f5dd-4188-98b8-5433462131e4)

I am trying to calculate delta(tau) = (I_E - I_L) ./ (2 * I_P). This is one of many traditional spoofing detection methods.

If you look at the output of FGI-GSRx, I only have one outputs of I_E & I_L while I have many outputs of I_P.

I was expecting that I_E & I_L have same number of outputs as I_P...

or

in my equation, would only I_P be the changing values and I_E & I_L remain constant?

Am I missing something?

**Comment by zahidulbhuiyan** [comment]
Hi! tortuga3750,

I was on holidays. Sorry for the delay in replying you back. For the sake of not consuming a huge memory, FGI-GSRx v2.0.0 do not save all the tracking parameters like its predecessor v1.0.0. You just need to change the variable declaration, and save the corresponding epoch-by-epoch I_E and I_L values similar to I_P values. Good luck!

**Comment by tortuga3750** [comment]
> Hi! tortuga3750,
> 
> I was on holidays. Sorry for the delay in replying you back. For the sake of not consuming a huge memory, FGI-GSRx v2.0.0 do not save all the tracking parameters like its predecessor v1.0.0. You just need to change the variable declaration, and save the corresponding epoch-by-epoch I_E and I_L values similar to I_P values. Good luck!


thank you so much..

Could you please offer some help on my post  "Could you please share your GPS param file for OAKBAT dataset? #5"?

thank you again...
